# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7909473f9aa756963ecb2a1b0f938d036f0894fc5fec51be5b602c7852fd3d1ffe442114dd5ad5111c29e7e9cdf5b483838c234f13fee7fb082c1e921d95bda1

test:
  secret_key_base: fff748a22f92ef39815ab0b8721d7cbce96ac625bce43da0077e4860bfadcb27ff3943cbc5a0caf561456d02a25d9e791c74fba631ab3fcf696fffffc18e1fb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
